trigger:
- 'k8s'

stages:
  - stage: 'Build'
    displayName: 'Build kubernetes application'
    jobs: 
    - job: 'Build'
      displayName: 'Build job'
      pool:
        vmImage: 'ubuntu-18.04'
      steps:
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'Create container registry'
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'kube-connection'
            subscriptionId: '31913d88-00fe-439b-9bab-a0fc309af11f'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'kubepipe'
            location: 'West Europe'
            templateLocation: 'Linked artifact'
            csmFile: 'k8s.json'
            overrideParameters: '-clientId "$(clientId)" -clientSecret "$(clientSecret)" -sshPub "$(ssh_pub)"'
            deploymentMode: 'Incremental'

        - task: Kubernetes@1
          displayName: 'create kubectl'
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: 'test-kube-connection'
            namespace: 'default'
            command: 'apply'
            arguments: '-f azure-vote-all-in-one-redis.yaml'
        
        - publish: '$(Build.SourcesDirectory)'
          displayName: 'create dev artifact'
          artifact: dev
        - publish: '$(Build.SourcesDirectory)'
          displayName: 'create stage artifact'
          artifact: stage
